services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "MessageHawk_Dev_123"
    ports:
      - "1433:1433"

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    ports:
      - "5206:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=MessageHawk;User Id=sa;Password=MessageHawk_Dev_123;TrustServerCertificate=True;MultipleActiveResultSets=true"
      RabbitMq__HostName: rabbitmq
      Authentication__DisableJwt: "true"
    depends_on:
      - sqlserver
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=MessageHawk;User Id=sa;Password=MessageHawk_Dev_123;TrustServerCertificate=True;MultipleActiveResultSets=true"
      RabbitMq__HostName: rabbitmq
    depends_on:
      - sqlserver
      - rabbitmq
